event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('create_event', views.create_event, name="create_event"),
]

event_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("event/", include("event.urls")),
    path("", include("users.urls")),
    path("profile/", include("profil_pengguna.urls")),
    path("dompet/", include("dompet_digital.urls")),
    path("testimoni/", include("testimoni.urls")),
    path("transaksi/", include("transaksi.urls"))
]

event/models.py
from django.db import models

# Create your models here.

event/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import connection

# Create your views here.
def index(request):
    with connection.cursor() as cursor:
        if request.session.get("username", False):
            username = request.session.get("username")
            cursor.execute(f"SELECT * FROM EVENT WHERE owner = '{username}'")  
        else:  
            username = None
            cursor.execute("SELECT * FROM EVENT")

        row = cursor.fetchall()
        
        context = {
            "event_query" : row,
            "username" : username
        }

        return render(request, "event/events.html", context)

def login(request):
    try:
        username = request.session["username"]
    except KeyError:
        username = None

    context = {
        "username" : username
    }
    if request.method == "POST":
        request.session["username"] = "owner_one"
        return redirect("event:login")

    return render(request, "event/login.html", context)

def logout(request):
    try:
        request.session.pop("username")
    except KeyError:
        pass
    return redirect("event:login")

def create_event(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            name = request.POST["name"]
            number = request.POST["number"]
            
            # Get username
            if request.session.get("username", False):
                # kalau logged in
                owner = request.session["username"]
            else:
                owner = request.POST["owner"]

            query = f"""
                INSERT INTO EVENT (name, number, owner) VALUES
                ('{name}', {number}, '{owner}')
            """
            cursor.execute(query)

            return redirect("event:index")

    context = {
        "username" : request.session.get("username", None)
    }
    
    return render(request, "event/create_event.html", context)

event/templates/event/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Basdat Testing</title>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% if username %}
        <h3>Welcome {{username}}, <a href="{% url 'event:logout' %}">logout</a></h3>
    {% else %}
        <h3>You aren't logged in! <a href="{% url 'event:login' %}">Login</a></h3>
    {% endif %}

    <h4>See events <a href="{% url 'event:index' %}">here</a></h4>
    <h4>Make your own events <a href="{% url 'event:create_event' %}">here</a></h4>
    {% block content %}
    {% endblock %}
</body>
</html>

event/templates/event/create_event.html
{% extends "event/base.html" %}
{% block content %}

    <form method="POST" action="{% url 'event:create_event' %}">
        {% csrf_token %}

        {% if username %}
            <h3>Creating event for {{username}}</h3>
        {% else %}
            <input name="owner" placeholder="Owner's name">
        {% endif %}

        <input name="name" placeholder="Event name">
        <input name="number" type="number" placeholder="Event number">
        <input type="submit" value="Create Event">


    </form>

{% endblock %}

event/templates/event/events.html
{% extends "event/base.html" %}
{% block content %}

    {% if username %}
        <h1>Showing events for the organizer: '{{username}}'</h1>
    {% else %}
        <h1>Showing all events</h1>
    {% endif %}

    {% for event in event_query %}
        <h3>{{event.0}}</h3>
        <div>Made by {{event.2}}</div>
        <div>Number: {{event.1}}</div>
    {% endfor %}

{% endblock %}

event/templates/event/login.html
{% extends "event/base.html" %}
{% block content %}

    {% if username %}
        <form action="{% url 'event:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Logout">
        </form>
    {% else %}
        <form action="{% url 'event:login' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Log in as owner_one">
        </form>
    {% endif %}
    
    <br>
    <a href="{% url 'event:index' %}">See Events</a>
{% endblock %}