event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('create_event', views.create_event, name="create_event"),
]

event_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("event/", include("event.urls")),
    path("", include("users.urls")),
    path("profile/", include("profil_pengguna.urls")),
    path("dompet/", include("dompet_digital.urls")),
    path("testimoni/", include("testimoni.urls")),
    path("transaksi/", include("transaksi.urls"))
]

transaksi/urls.py
from django.urls import path, include
from . import views

app_name = "transaksi"

urlpatterns = [
    path("", views.index, name="index"),
    path("pesan_tiket/<int:event>", views.pesan_tiket,name="pesan_tiket"),
    path("allevents/", views.allevents, name="allevents")
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("register_pengunjung", views.register_pengunjung, name="register_pengunjung"),
    path("register_organizer", views.register_organizer, name="register_organizer"),
    path("tambah_event", views.tambah_event, name="tambah_event"),
    path("daftar_event", views.daftar_event, name="daftar_event"),
    path("update_event/<str:id_event>", views.update_event, name="update_event"),
    path("delete_event/<str:id_event>", views.delete_event, name="delete_event")
]

event/models.py
from django.db import models

# Create your models here.

transaksi/models.py
from django.db import models

# Create your models here.

event/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import connection

# Create your views here.
def index(request):
    with connection.cursor() as cursor:
        if request.session.get("username", False):
            username = request.session.get("username")
            cursor.execute(f"SELECT * FROM EVENT WHERE owner = '{username}'")  
        else:  
            username = None
            cursor.execute("SELECT * FROM EVENT")

        row = cursor.fetchall()
        
        context = {
            "event_query" : row,
            "username" : username
        }

        return render(request, "event/events.html", context)

def login(request):
    try:
        username = request.session["username"]
    except KeyError:
        username = None

    context = {
        "username" : username
    }
    if request.method == "POST":
        request.session["username"] = "owner_one"
        return redirect("event:login")

    return render(request, "event/login.html", context)

def logout(request):
    try:
        request.session.pop("username")
    except KeyError:
        pass
    return redirect("event:login")

def create_event(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            name = request.POST["name"]
            number = request.POST["number"]
            
            # Get username
            if request.session.get("username", False):
                # kalau logged in
                owner = request.session["username"]
            else:
                owner = request.POST["owner"]

            query = f"""
                INSERT INTO EVENT (name, number, owner) VALUES
                ('{name}', {number}, '{owner}')
            """
            cursor.execute(query)

            return redirect("event:index")

    context = {
        "username" : request.session.get("username", None)
    }
    
    return render(request, "event/create_event.html", context)

transaksi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import connection
import datetime

def index(request):
    with connection.cursor() as cursor:
        cursor.execute(f"""
                        SELECT id_event, nama, tanggal_mulai, tanggal_selesai, jam_mulai, jam_selesai
            deskripsi, kapasitas_total, kapasitas_total_tersedia FROM EVENT""")

        row = cursor.fetchall()

        pengguna = request.session.get("pengguna")

        context = {

            "event_query" : row,
            "pengguna" : pengguna
        }

    return render(request, "transaksi/index.html", context=context)

def pesan_tiket(request, event):
    if request.session.get("tipe", None) != "Pengunjung":
        return redirect("users:landing")

    with connection.cursor() as cursor :
        cursor.execute(f"""SELECT * FROM EVENT e NATURAL JOIN TEMA  WHERE e.id_event = '{event}'""")

        row = cursor.fetchall()
        id_event = row[0][0]
        nama_event = row[0][1]
        tanggal_mulai = row[0][2]
        tanggal_selesai = row[0][3]
        jam_mulai = row[0][4]
        jam_selesai = row[0][5]
        deskripsi = row[0][6]
        kapasitas = row[0][7]
        kapasitas_tersedia = row[0][8]
        id_tipe = row[0][9]
        email_organizer = row[0][10]

        cursor.execute(f"""SELECT nama_tipe FROM TIPE WHERE id_tipe = '{id_tipe}'""")

        row2 = cursor.fetchall()
        nama_tipe = row2[0][0]

        cursor.execute(f"""SELECT nama_tema FROM TEMA NATURAL JOIN EVENT e WHERE e.id_event = '{event}'""")
        row3 = cursor.fetchall()
        nama_tema = row3[0][0]

        cursor.execute(f"""SELECT kota FROM LOKASI NATURAL JOIN LOKASI_PENYELENGGARAAN_EVENT l WHERE l.id_event = '{event}'""")
        row4 = cursor.fetchall()
        nama_lokasi = row4[0][0]

        cursor.execute(f"""select nama_kelas, tarif, kapasitas, kapasitas_tersedia from kelas_tiket where nama_kelas = 'Silver'""")
        row5 = cursor.fetchall()
        kelas_tiket_silver = row5[0][0]
        tarif_tiket_silver = row5[0][1]
        kapasitas_tiket_silver = row5[0][2]
        kapasitas_tersedia_tiket_silver = row5[0][3]

        request.session['id_event'] = id_event
        request.session['tarif_tiket_silver'] = tarif_tiket_silver



    context = {
        'id_event' : id_event,
        'nama_event' : nama_event,
        'id_tipe' : id_tipe,
        'nama_tipe' : nama_tipe,
        'nama_tema' : nama_tema,
        'deskripsi' : deskripsi,
        'tanggal_mulai' : tanggal_mulai,
        'tanggal_selesai' : tanggal_selesai,
        'nama_lokasi' : nama_lokasi,
        'kelas_tiket_silver' : kelas_tiket_silver,
        'tarif_tiket_silver' : tarif_tiket_silver,
        'kapasitas_tiket_silver' : kapasitas_tiket_silver,
        'kapasitas_tersedia_tiket_silver' : kapasitas_tersedia_tiket_silver
    }


    return render(request, "transaksi/tiket.html", context = context)

def allevents(request) :
    list_nama_daftar = request.GET.getlist("Name")
    list_email_daftar = request.GET.getlist("Email")

    print("TARIF TIKET SESSION ", request.session['tarif_tiket_silver'])
    total_bayar = int(request.session['tarif_tiket_silver'])

    print("LEN DAFTAR NAMA ", len(list_nama_daftar))

    total_bayar = total_bayar * len(list_nama_daftar)

    print("TOTAL BAYAR ", total_bayar)
    # if request.method == "GET" :
    #     print("REQUEST SESSION ID_EVENT",request.session.get("id_event"))
    #     with connection.cursor() as cursor:
    #         DATE = datetime.date.today()
    #         TIME = datetime.datetime.now().strftime('%H:%M:%S')
    #
    #         cursor.execute(f"""INSERT INTO TRANSAKSI(email_pengunjung, waktu, tanggal,
    #                 status, total_bayar) VALUES('{request.session.get("email")}',
    #                 '{DATE}','{TIME}','Belum Dibayar','{total_bayar}' )""")
    #
    #         cursor.execute(f"""INSERT INTO DAFTAR_TIKET (email_pengunjung, email_pemilik_tiket, waktu_transaksi, tanggal_transaksi, nama_pemilik_tiket, id_event, nama_kelas)
    #                 VALUES('{request.session.get("email")}', '{request.GET.get('Email','')}', '{TIME}', '{DATE}', '{request.GET.get('Name','')}', '{request.session['id_event']}','Silver')""")
    #



    return render(request, "transaksi/events.html")

transaksi/templates/transaksi/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- CSS External -->
    <link rel="stylesheet" href="{% static 'transaksi.css' %}">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'javascript/table_row.js' %}"></script>
    <title>Event+</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-1">
      <div class="container">
        <a class="navbar-brand" href="{% url 'users:landing' %}">Event+</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:landing' %}">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>

          <!-- Case belum login -->
          {% if not request.session.pengguna %}
            <a href="{% url 'users:login' %}">
              <button class="btn btn-info">
                Login
              </button>
            </a>
          <!-- Case sudah login -->
          {% else %}
            <h5 class="text-light m-0 p-0 mr-2">Selamat datang, {{request.session.pengguna}}</h5>
            <a href="{% url 'users:logout' %}">
              <button class="btn btn-danger">
                Logout
              </button>
            </a>
          {% endif %}

        </div>
        </div>
    </nav>


    <div class="main-container bg-3">
        {% block content %}
        {% endblock %}
    </div>


    <div class="d-flex justify-content-center align-items-center height-nav bg-1 text-light">
        Made by Kelompok 3 - Basis Data (J) Reguler Gasal 2020/2021
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- JS External -->
    <script src="{% static 'users_js/reg_organizer.js' %}"></script>

  </body>
</html>

transaksi/templates/transaksi/events.html
{% extends "users/base.html" %}
{% block content %}
{% load static %}

<div>
    <h1>Selamat {{request.session.pengguna}}. Pendaftaran berhasil dilakukan</h1>
</div>







{% endblock %}

transaksi/templates/transaksi/index.html
{% extends "users/base.html" %}
{% block content %}


<div class="container py-3">

<!--    {% if messages %}-->
<!--      {% for message in messages %}-->
<!--        <div class="alert alert-{{message.tags}} fade show" role="alert">-->
<!--          {{message}}-->
<!--        </div>-->
<!--      {% endfor %}-->
<!--    {% endif %}-->

    <div class="d-flex justify-content-center">
        <h1>Show all available event for {{pengguna}}</h1>
    </div>



    <table class="table mt-3">
        <thead class="bg-1">
          <tr>
            <th scope="col">Nama Event</th>
            <th scope="col">Tanggal Mulai</th>
            <th scope="col">Tanggal Selesai</th>
            <th scope="col">Jam Mulai</th>
            <th scope="col">Jam Selesai</th>
            <th scope="col">Kapasitas</th>
            <th scope="col">Tiket Tersedia</th>
          </tr>
        </thead>
        <tbody>
            {% for event in event_query %}
                <tr class="bg-4 {{dompet.4}}">
                    <th scope="row">{{event.1}}</th>
                    <td>{{event.2}}</td>
                    <td>{{event.3}}</td>
                    <td>{{event.4}}</td>
                    <td>{{event.5}}</td>
                    <td>{{event.6}}</td>
                    <td>{{event.7}}</td>

                    <td>
                        <a href="{% url 'transaksi:pesan_tiket' event.0 %}">
                            [Pesan Tiket]
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>

</div>

{% endblock %}

transaksi/templates/transaksi/tiket.html
{% extends "users/base.html" %}
{% block content %}
{% load static %}

<head>
        <script type="text/javascript" src="{% static 'javascript/table_row.js' %}"></script>

</head>

<h1> Pesan Tiket Event</h1>

<div id="deksripsi">
    <h6>Tema Event : {{nama_tema}}</h6>
    <h6>Nama Event : {{nama_event}}</h6>
    <h6>Deskripsi : {{deskripsi}}</h6>
    <h6>Tanggal : {{tanggal_mulai}} - {{tanggal_selesai}}</h6>
    <h6>Lokasi : {{nama_lokasi}}</h6>
    <h6>Tipe Event : {{nama_tipe}}</h6>
</div>
<br>
<br>
<div>
{% if kelas_tiket_silver %}
<form method="GET"  action="{% url 'transaksi:allevents'%}">
    {% csrf_token %}

      <ul>Kelas : {{kelas_tiket_silver}} - Tarif : Rp.{{tarif_tiket_silver}} - kapasitas :{{kapasitas_tersedia_tiket_silver}}  - kapasitas tersedia : {{kapasitas_tersedia_tiket_silver}}</ul>
      <table id="tbl">
          <tbody>
   <tr >
      <td><input type="text" name="Name" placeholder="Nama Pemesan" /></td>
      <td><input type="text" name="Email" placeholder="Email Pemesan" /></td>
      <td><input type="button" id="btn-delete-row" value="Delete Row" /></td>
    </tr>

          </tbody>
</table>
    <input type="button" class="button add_another" value="Tambah jumlah tiket"/>


{% else %}
      <h1>Maaf tidak ada tiket yang tersedia</h1>
{% endif %}
<div>
    <button type="submit"  id="pesan_btn" class="btn btn-success">
        Pesan
      </button>
      </div>

      </form>

</div>





{% endblock %}