event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('create_event', views.create_event, name="create_event"),
]

event_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("event/", include("event.urls")),
    path("", include("users.urls")),
    path("profile/", include("profil_pengguna.urls")),
    path("dompet/", include("dompet_digital.urls")),
    path("testimoni/", include("testimoni.urls")),
    path("transaksi/", include("transaksi.urls"))
]

testimoni/urls.py
from django.urls import path
from . import views

app_name = "testimoni"

urlpatterns = [
    path('', views.lihatTestimoni, name="testimoni_view"),
    path('edit/', views.editTestimoni, name="edit_testimoni"),
    path('delete/', views.deleteTestimoni, name="delete_testimoni"),
    path('create/', views.createTestimoni, name="create_testimoni"),
    path('transaksi/', views.bayarTransaksi, name="bayar_transaksi"),
    path('transaksi/proses', views.prosesTransaksi, name="proses_transaksi"),
]

testimoni/models.py
from django.db import models

# Create your models here.

testimoni/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import connection

from datetime import datetime

def lihatTestimoni(request):
    # Check sudah logged in sebagai pengunjung / tidak
    if request.session.get("tipe", None) != "Pengunjung":
        return redirect("users:landing")

    if request.method == "POST":
        print(request.POST)
        
        request.session['email_pemilik_tiket'] = request.POST['email_pemilik_tiket']
        request.session['waktu_transaksi'] = request.POST['waktu_transaksi']
        request.session['tanggal_transaksi'] = request.POST['tanggal_transaksi']
        request.session['timestamp_testimoni'] = request.POST['timestamp_testimoni']
        
        return redirect("testimoni:delete_testimoni")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT T.timestamp_testimoni,E.nama, T.rating, T.isi, T.foto, D.id_event, 
            T.email_pemilik_tiket, T.waktu_transaksi, T.tanggal_transaksi, T.timestamp_testimoni 
            FROM TESTIMONI T, EVENT E , DAFTAR_TIKET D
            WHERE T.email_pengunjung = D.email_pengunjung 
            AND D.id_event = E.id_event 
            AND D.email_pengunjung = '{request.session["email"]}'
            AND D.waktu_transaksi = T.waktu_transaksi
            AND D.tanggal_transaksi = T.tanggal_transaksi
            AND D.email_pemilik_tiket = T.email_pemilik_tiket
        """)

        row = cursor.fetchall()

        testimoni_query = [
            (no, item[0], item[1], item[2], item[3], item[4],item[5],item[6],item[7],item[8],item[9]) for (no, item)
            in enumerate(row, start=1)
        ]
        print(testimoni_query)
        context = {
            "testimoni_query" : testimoni_query,  
        }

    return render(request, "testimoni/testimoni.html", context=context)

def editTestimoni(request):
    # Check sudah logged in sebagai pengunjung / tidak
    if request.session.get("tipe", None) != "Pengunjung":
        return redirect("users:landing")

    if request.method == "POST":
        print(request.POST)
        
        if(request.POST['status'] == "CANCEL"):
            messages.add_message(request, messages.WARNING, f'Update testimoni telah gagal!')
            return redirect("testimoni:testimoni_view")

        with connection.cursor() as cursor:
            cursor.execute(f"""
                SELECT  T.email_pemilik_tiket, 
                T.waktu_transaksi, T.tanggal_transaksi, T.timestamp_testimoni 
                FROM TESTIMONI T, EVENT E , DAFTAR_TIKET D
                WHERE T.email_pengunjung = D.email_pengunjung 
                AND D.id_event = E.id_event 
                AND T.email_pengunjung = '{request.session["email"]}'
                AND E.nama = '{request.POST["nama_event"]}'
                AND D.email_pengunjung = '{request.session["email"]}'
                AND D.waktu_transaksi = T.waktu_transaksi
                AND D.tanggal_transaksi = T.tanggal_transaksi
                AND D.email_pemilik_tiket = T.email_pemilik_tiket
            """)

            row = cursor.fetchall()
            
            testimoni_query = [
            (item[0], item[1], item[2], item[3]) for (no, item) in
            enumerate(row, start=1)
            ]
            email_pemilik_tiket= testimoni_query[0][0]
            waktu_transaksi= testimoni_query[0][1]
            tanggal_transaksi= testimoni_query[0][2]
            timestamp_testimoni= testimoni_query[0][3]
            print(testimoni_query)

        with connection.cursor() as cursor:
            cursor.execute(f"""
                UPDATE TESTIMONI
                SET rating = '{request.POST["rating"]}', 
                foto = '{request.POST["foto"]}', 
                isi = '{request.POST["isi"]}'
                WHERE TESTIMONI.email_pengunjung = '{request.session["email"]}'
                AND TESTIMONI.email_pemilik_tiket= '{email_pemilik_tiket}'
                AND TESTIMONI.waktu_transaksi= '{waktu_transaksi}'
                AND TESTIMONI.tanggal_transaksi= '{tanggal_transaksi}'
                AND TESTIMONI.timestamp_testimoni = '{timestamp_testimoni}'
            """)
            messages.add_message(request, messages.SUCCESS, f'Update testimoni telah berhasil!')

        return redirect("testimoni:testimoni_view")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT E.nama, T.rating, T.foto, T.isi, T.email_pemilik_tiket, 
            T.waktu_transaksi, T.tanggal_transaksi, T.timestamp_testimoni 
            FROM TESTIMONI T, EVENT E , DAFTAR_TIKET D
            WHERE T.email_pengunjung = D.email_pengunjung 
            AND D.id_event = E.id_event 
            AND T.email_pengunjung = '{request.session["email"]}'
            AND D.waktu_transaksi = T.waktu_transaksi
            AND D.tanggal_transaksi = T.tanggal_transaksi
            AND D.email_pemilik_tiket = T.email_pemilik_tiket
        """)

        row = cursor.fetchall()

        testimoni_query = [
            (no, item[0], item[1], item[2], item[3], item[4],item[5], item[6], item[7]) for (no, item) in
            enumerate(row, start=1)
        ]

        context = {
            "selected_testimoni_query" : testimoni_query,
        }

    return render(request, "testimoni/updateTestimoni.html",context=context)



def deleteTestimoni(request):
    # Check sudah logged in sebagai pengunjung / tidak
    if request.session.get("tipe", None) != "Pengunjung":
        return redirect("users:landing")

    if request.method == "POST":
        print(request.POST['status'])
        if(request.POST['status'] == "CANCEL"):
            messages.add_message(request, messages.WARNING, f'Penghapusan testimoni telah dibatalkan!')
            return redirect("testimoni:testimoni_view")

        with connection.cursor() as cursor:
            cursor.execute(f"""
                DELETE FROM TESTIMONI 
                WHERE TESTIMONI.email_pemilik_tiket = '{request.session['email_pemilik_tiket']}'
                AND TESTIMONI.email_pengunjung = '{request.session["email"]}'
            """)
        
        messages.add_message(request, messages.SUCCESS, f'Penghapusan testimoni telah berhasil!')
        
        
        return redirect("testimoni:testimoni_view")
    
    return render(request, "testimoni/delete_testimoni_confirmation.html")


def createTestimoni(request):
    # Check sudah logged in sebagai pengunjung / tidak
    if request.session.get("tipe", None) != "Pengunjung":
        return redirect("users:landing")


    if request.method == "POST":
        print(request.POST)

        if(request.POST['status'] == "CANCEL"):
            messages.add_message(request, messages.WARNING, f'Pembuatan testimoni telah dibatalakan!')
            return redirect("testimoni:testimoni_view")

        with connection.cursor() as cursor:
            cursor.execute(f"""
                SELECT  D.email_pemilik_tiket,D.waktu_transaksi, D.tanggal_transaksi
                FROM EVENT E , DAFTAR_TIKET D
                WHERE D.id_event = E.id_event 
                AND D.email_pengunjung = '{request.session["email"]}'
                AND E.nama = '{request.POST["nama_event"]}'
            """)

            row = cursor.fetchall()
            
            testimoni_query = [
            (item[0], item[1], item[2]) for (no, item) in
            enumerate(row, start=1)
            ]

            email_pemilik_tiket= testimoni_query[0][0]
            waktu_transaksi= testimoni_query[0][1]
            tanggal_transaksi= testimoni_query[0][2]
            timestamp_testimoni= datetime.now()
            print(waktu_transaksi)
            print(timestamp_testimoni)

            cursor.execute(f""" INSERT INTO TESTIMONI VALUES
                ('{request.session["email"]}', '{email_pemilik_tiket}','{waktu_transaksi}', '{tanggal_transaksi}','{timestamp_testimoni}',
                '{request.POST["foto"]}','{request.POST["isi"]}','{request.POST["rating"]}')
            """)
            

        
        messages.add_message(request, messages.SUCCESS, f'Pembuatan testimoni telah berhasil!')

        return redirect("testimoni:testimoni_view")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT DISTINCT E.nama,
            D.email_pemilik_tiket,D.waktu_transaksi, D.tanggal_transaksi
            FROM EVENT E , DAFTAR_TIKET D
            WHERE D.id_event = E.id_event 
            AND D.email_pengunjung = '{request.session["email"]}'
            AND D.email_pemilik_tiket NOT IN(
                SELECT email_pemilik_tiket FROM TESTIMONI
            )
        """)

        row = cursor.fetchall()

        testimoni_query = [
            (no, item[0], item[1], item[2], item[3]) for (no, item) in
            enumerate(row, start=1)
        ]

        
        
        if(len(testimoni_query) <= 0):
            messages.add_message(request, messages.WARNING, f'Semua event yang telah diikuti telah dibuat testimoninya!')
            return redirect("testimoni:testimoni_view")

        print(testimoni_query)

        context = {
            "selected_testimoni_query" : testimoni_query,
        }    
    
    return render(request, "testimoni/create_testimoni.html",context=context)



def to_rupiah_notation(angka):
    return f'Rp {int(angka):,}'.replace(",",".") + ",00"

def bayarTransaksi(request):
    # Check sudah logged in sebagai pengunjung / tidak
    if request.session.get("tipe", None) != "Pengunjung":
        return redirect("users:landing")

    if request.method == "POST":
        print(request.POST)
        
        request.session['email_pengunjung'] = request.POST['email_pengunjung']
        request.session['waktu_transaksi'] = request.POST['waktu_transaksi']
        request.session['tanggal_transaksi'] = request.POST['tanggal_transaksi']
        request.session['no_akun_dompet'] = request.POST['no_akun_dompet']

testimoni/templates/testimoni/create_testimoni.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="container py-3">

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}


    <div class="d-flex justify-content-center">
        <h1>Buat Testimoni</h1>
    </div>

    
    <form method="POST" action="{% url 'testimoni:create_testimoni' %}">
		{% csrf_token %}
		<div class="d-flex align-items-center">
			<h4>Pilih Event :</h4>
			<select name="nama_event" id="nama_event_selector" class="ml-2">
			  {% for event in selected_testimoni_query %}
         <option value="{{event.1}}">{{event.1}}</option>
			  {% endfor %}
			</select>
		</div>
		<br>

      <div class="d-flex align-items-center">
        <h4 class="m-0 p-0">Rating</h4>
        <input name="rating" id="rating" type="number" oninput="validity.valid||(value='');" min="0" max="5" class="ml-1" value="" placeholder="Rating">
      </div>

      <br>

      <div class="d-flex align-items-center">
        <h4 class="m-0 p-0">Foto</h4>
        <input name="foto" id="foto" type="text"  class="form-width form-control ml-4" value="" >
      </div>

      <br>

      <div class="d-flex align-items-center">
        <h4 class="m-0 p-0">Isi</h4>
        <input name="isi" id="isi" type="text"  class="form-control ml-4" value="" >
      </div>
		
		

      <br>

      <button type="submit" id="topup_btn" class="btn btn-success" >
        Buat Testimoni
		  </button>
      <input type="hidden" name="status" id="status"  value="CREATE">

    </form>
    
    <form method="POST" action="{% url 'testimoni:create_testimoni' %}">
      {% csrf_token %}
      
      <button type="submit" id="topup_btn" class="btn btn-danger" >
        Cancel
	  	</button>
      <input type="hidden" name="status" id="status"  value="CANCEL">
    </form>

    

</div>

<script src="{% static 'dompet_js/topup.js' %}"></script>

{% endblock %}

testimoni/templates/testimoni/delete_testimoni_confirmation.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="container py-3">

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}


    
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <div class="d-flex justify-content-center">
        <h1>Hapus Testimoni</h1>
    </div>

    <div class="d-flex justify-content-center">
        <h1>Apakah  anda yakin untuk menghapus testimoni ini?</h1>
    </div>

    
    <form method="POST" action="{% url 'testimoni:delete_testimoni' %}" class = "d-flex justify-content-center">
		{% csrf_token %}

      <button type="submit" id="topup_btn" class="btn btn-success" >
        Ya
      </button>
      <input type="hidden" name="status" id="status"  value="DELETE">
    </form>

    <form method="POST" action="{% url 'testimoni:delete_testimoni' %}" class = "d-flex justify-content-center">
      {% csrf_token %}
      <button type="submit" id="topup_btn" class="btn btn-danger" >
        Tidak
      </button>
      <input type="hidden" name="status" id="status"  value="CANCEL">
    </form>

    

</div>

<script src="{% static 'dompet_js/topup.js' %}"></script>

{% endblock %}

testimoni/templates/testimoni/testimoni.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="container py-3">

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <div class="d-flex justify-content-center">
        <h1>Testimoni</h1>
    </div>

    
    <table class="table mt-3">
        <thead class="bg-1">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Timestamp</th>
            <th scope="col">Nama Event</th>
            <th scope="col">Rating</th>
            <th scope="col">Isi</th>
            <th scope="col">Foto</th>
            <th scope="col">[Edit]</th>
            <th scope="col">[Delete]</th>
          </tr>
        </thead>
        <tbody>
            {% for testimoni in testimoni_query %}
                <tr class="bg-4 {{testimoni.6}">
                    <th scope="row">{{testimoni.0}}</th>
                    <td>{{testimoni.1}}</td>
                    <td>{{testimoni.2}}</td>
                    <td>{{testimoni.3}}</td>
                    <td>{{testimoni.4}}</td>
                    <td>{{testimoni.5}}</td>
                    <td>
                        <a href="{% url 'testimoni:edit_testimoni' %}?testimoni={{testimoni.6}}" class="btn btn-danger">
                            Edit
                        </a>
                    </td>
                    <td>
                        <form method="POST" action="{% url 'testimoni:testimoni_view' %}">
                            {% csrf_token %}
                            <input type="hidden" name="email_pemilik_tiket" id="email_pemilik_tiket"  value="{{testimoni.7}}">
                            <input type="hidden" name="waktu_transaksi" id="waktu_transaksi"  value="{{testimoni.8}}">
                            <input type="hidden" name="tanggal_transaksi" id="tanggal_transaksi"  value="{{testimoni.9}}">
                            <input type="hidden" name="timestamp_testimoni" id="timestamp_testimoni"  value="{{testimoni.10}}">
                            <button type="submit" id="topup_btn" class="btn btn-danger">
                                Delete
                            </button>                   
                        </form>
                    </td>
                </tr>     
            {% endfor %}
        </tbody>
    </table>




</div>

<script src="{% static 'dompet_js/topup.js' %}"></script>

{% endblock %}

testimoni/templates/testimoni/updateTestimoni.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="container py-3">

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}


    
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <div class="d-flex justify-content-center">
        <h1>Update Testimoni</h1>
    </div>

    
    <form method="POST" action="{% url 'testimoni:edit_testimoni' %}">
		{% csrf_token %}
		<div class="d-flex align-items-center">
			<h4>Pilih Event :</h4>
			<select name="nama_event" id="nama_event_selector" class="ml-2">
			  {% for event in selected_testimoni_query %}
         <option value="{{event.1}}">{{event.1}}</option>
			  {% endfor %}
			</select>
		</div>
		<br>

      <div class="d-flex align-items-center">
        <h4 class="m-0 p-0">Rating</h4>
        <input name="rating" id="rating" type="number" oninput="validity.valid||(value='');" min="0" max="5" class="ml-4" value="" placeholder="Rating">
      </div>

      <br>

      <div class="d-flex align-items-center">
        <h4 class="m-0 p-0">Foto</h4>
        <input name="foto" id="foto" type="text"  class="form-width form-control ml-4" value="" >
      </div>

      <br>

      <div class="d-flex align-items-center">
        <h4 class="m-0 p-0">Isi</h4>
        <input name="isi" id="isi" type="text"  class="form-control ml-4" value="" >
      </div>
		
		

      <br>

      <button type="submit" id="topup_btn" class="btn btn-success" >
        Update Testimoni
	  	</button>
      <input type="hidden" name="status" id="status"  value="UPDATE">
    </form>
    <form method="POST" action="{% url 'testimoni:edit_testimoni' %}">
      {% csrf_token %}
      
      <button type="submit" id="topup_btn" class="btn btn-danger" >
        Cancel
	  	</button>
      <input type="hidden" name="status" id="status"  value="CANCEL">
    </form>

    

</div>

<script src="{% static 'dompet_js/topup.js' %}"></script>

{% endblock %}