dompet_digital/urls.py
from django.urls import path
from . import views

app_name = "dompet"

urlpatterns = [
    path("", views.dompet_view, name="dompet_view"),
    path("topup", views.topup_dompet, name="topup_dompet"),
]

event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('create_event', views.create_event, name="create_event"),
]

event_plus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("event/", include("event.urls")),
    path("", include("users.urls")),
    path("profile/", include("profil_pengguna.urls")),
    path("dompet/", include("dompet_digital.urls")),
    path("testimoni/", include("testimoni.urls")),
    path("transaksi/", include("transaksi.urls"))
]

profil_pengguna/urls.py
from django.urls import path, include
from . import views

app_name = "profil_pengguna"

urlpatterns = [
    path("", views.profil, name="profile"),
    path("organizer", views.profil_organizer, name="profil_organizer"),
    path("profil/pengunjung", views.profil_pengunjung, name="profil_pengunjung"),
    path("profil/edit/pengunjung", views.edit_pengunjung, name="edit_pengunjung"),
    path("profil/edit/organizer", views.edit_organizer, name="edit_organizer"),
]

testimoni/urls.py
from django.urls import path
from . import views

app_name = "testimoni"

urlpatterns = [
    path('', views.lihatTestimoni, name="testimoni_view"),
    path('edit/', views.editTestimoni, name="edit_testimoni"),
    path('delete/', views.deleteTestimoni, name="delete_testimoni"),
    path('create/', views.createTestimoni, name="create_testimoni"),
    path('transaksi/', views.bayarTransaksi, name="bayar_transaksi"),
    path('transaksi/proses', views.prosesTransaksi, name="proses_transaksi"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("register_pengunjung", views.register_pengunjung, name="register_pengunjung"),
    path("register_organizer", views.register_organizer, name="register_organizer"),
    path("tambah_event", views.tambah_event, name="tambah_event"),
    path("daftar_event", views.daftar_event, name="daftar_event"),
    path("update_event/<str:id_event>", views.update_event, name="update_event"),
    path("delete_event/<str:id_event>", views.delete_event, name="delete_event")
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.db import connection, IntegrityError
from django.db.utils import InternalError
from django.contrib import messages
from .validators import validate_password, validate_name
from datetime import datetime
import random

def landing(request):
    response = {}
    response['events'] = []
    with connection.cursor() as cursor:
        cursor.execute("SELECT * from event e left outer join perusahaan p on e.email_organizer = p.email left outer join individu i on e.email_organizer = i.email left outer join lokasi l on e.id_event=(select id_event from lokasi_penyelenggaraan_event where id_event = e.id_event and kode_lokasi = l.kode) order by e.tanggal_mulai desc;")
        Anevent = cursor.fetchall()
        for i in range(len(Anevent)):
            cursor.execute("SELECT NAMA_TEMA FROM TEMA WHERE ID_event = %s", [Anevent[i][0]])
            tema_tuple = cursor.fetchall()
            theme = []
            for tema in tema_tuple:
                theme.append(tema[0])


            if Anevent[i][12] is None:
                # Kalau ternyata individu
                response['events'].append([
                    Anevent[i][1],
                    ', '.join(theme),
                    Anevent[i][7],
                    Anevent[i][8],
                    f"{Anevent[i][2]} - {Anevent[i][3]}", # tanggal berapa ke berapa
                    f"{Anevent[i][4]} - {Anevent[i][5]}", # jam berapa ke berapa
                    Anevent[i][20],
                    " ".join([Anevent[i][15],
                    Anevent[i][16]]),
                    request.session.get("email",None) == Anevent[i][11], # status milik dia / bukan
                    Anevent[i][2] > datetime.now().date(), # sudah lewat atau belum eventnya
                    Anevent[i][0] # id_event
                ]) 
            else:
                # Kalau ternyata organizer
                response['events'].append(
                    [Anevent[i][1], 
                    ', '.join(theme), 
                    Anevent[i][7],
                    Anevent[i][8], 
                    f"{Anevent[i][2]} - {Anevent[i][3]}", # tanggal berapa ke berapa
                    f"{Anevent[i][4]} - {Anevent[i][5]}", # jam berapa ke berapa
                    Anevent[i][20], 
                    Anevent[i][12], 
                    request.session.get("email",None) == Anevent[i][11], # last = status milik dia / bukan
                    Anevent[i][2] > datetime.now().date(), # sudah lewat atau belum eventnya
                    Anevent[i][0] # id_event
                ]) 
                

    return render(request, "users/index.html", response)

def delete_event(request, id_event):
    if request.method == "POST":   
        with connection.cursor() as cursor:
            cursor.execute(f"DELETE FROM EVENT WHERE id_event = '{id_event}'")
        return redirect("users:daftar_event")

    context = {}

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT id_event, nama FROM EVENT WHERE id_event = '{id_event}'")
        result = cursor.fetchall()
        context["nama_event"] = result[0][1]
        context["id_event"] = result[0][0]

    return render(request, "users/delete_event.html", context=context)


def tambah_event(request):
    if request.method == "POST":
        fail_status = False # asumsi input benar
        with connection.cursor() as cursor:

            # IN CASE INSERT GAGAL
            # Koleksi data2 yang dimasukkan dan suruh dia cek data lagi
            context_gagal = {
                "lokasi" : [], # isi (nomor, nama gedung, kota, alamat)
                "kls_tiket" : [], # isi (nomor, nama kelas, tarif, kapasitas)
                "tema_lst" : [] # isi (idx, nama_tema, True/False dari dipilih/tdk)
            }

            # Gather data gedung, kelas_tiket dll
            for key, value in request.POST.items():
                number = key.split("_")[-1] # nomor identifier gedung_1 misal
                if "gedung_" in key:
                    context_gagal["lokasi"].append(
                        # nomor, nama gedung, kota, alamat
                        (f"t{number}", value, request.POST[f"kota_{number}"], request.POST[f"alamat_{number}"])
                    )
                    # Kalau salah satu "" maka akan dianggap tidak valid, dan disuruh isi ulang
                    if request.POST[f"gedung_{number}"] == "" or request.POST[f"kota_{number}"] == "" or request.POST[f"alamat_{number}"] == "":
                        fail_status = True # tidak lanjut ke save procedure

                elif "nama_kelas_" in key:
                    context_gagal["kls_tiket"].append(
                        (f"t{number}", value, request.POST[f"tarif_{number}"], request.POST[f"kapasitas_{number}"])
                    )
                    if request.POST[f"nama_kelas_{number}"] == "" or request.POST[f"tarif_{number}"] == "" or request.POST[f"kapasitas_{number}"] == "":
                        fail_status = True # tidak lanjut ke save procedure
            
            # URUS TEMA
            # get tema yang di pilih
            tema_chosen = [
                value for key, value in request.POST.items() if "tema_" in key
            ]

            # Fetch semua TEMA di table
            cursor.execute(f"""
                SELECT DISTINCT nama_tema FROM TEMA
            """)
            tema_lst = cursor.fetchall()

            # Bagi tema ke yang berelasi ke event / tidak
            # (nama_tema, True/False)
            context_gagal["tema_lst"] = [
                (f"t{idx + 1}", tema[0], tema[0] in tema_chosen) for idx, tema in enumerate(tema_lst)
            ]
            
            # Apakah dari ngecek lokasi dan kelas_tiket ada yang fail (kosong)?
            if fail_status:
                messages.add_message(request, messages.WARNING, f"Tambah event gagal, Check kembali pengisian.")
                return render(request, "users/tambah_event.html", context=context_gagal)


            # Check apakah TIPE instance sudah ada?
            cursor.execute(f"""
                SELECT id_tipe FROM TIPE WHERE nama_tipe = '{request.POST["tipe_event"]}'
            """)

            result = cursor.fetchall()

            # Apabila tidak ada maka buat instance baru
            if (len(result) == 0):
                id_tipe = random.randint(1000000,9999999)
                cursor.execute(f"""
                    INSERT INTO TIPE (id_tipe, nama_tipe) VALUES
                    ('{id_tipe}', '{request.POST["tipe_event"]}')
                """)
            else:
                id_tipe = result[0][0] # Get id_tipe dari SELECT

            # Bikin instance EVENT 
            id_event = random.randint(1000000, 9999999)
            cursor.execute(f"""
                INSERT INTO EVENT (id_event, nama, tanggal_mulai, tanggal_selesai, jam_mulai,
                jam_selesai, deskripsi, kapasitas_total, kapasitas_total_tersedia,
                id_tipe, email_organizer)
                VALUES
                (
                    '{id_event}', '{request.POST["name"]}', '{request.POST["tmulai"]}', '{request.POST["tselesai"]}', '{request.POST["jmulai"]}',
                    '{request.POST["jselesai"]}', '{request.POST["desc"]}', 0, 0,
                    {id_tipe}, '{request.session["email"]}'        
                )
                """)

            # Bikin instance-instance TEMA, LOKASI, dan KELAS_TIKET
            for key, value in request.POST.items():
                if "tema_" in key: # Case TEMA
                    cursor.execute(f"""
                        INSERT INTO TEMA (id_event, nama_tema)
                        VALUES ('{id_event}', '{value}')
                    """)
                elif "nama_kelas_" in key: # Case KELAS_TIKET
                    number = key.split("_")[-1] # Angka yang ada diakhir2 key
                    cursor.execute(f"""
                        INSERT INTO KELAS_TIKET (id_event, nama_kelas, tarif,
                        kapasitas, kapasitas_tersedia)
                        VALUES (
                            '{id_event}', '{value}', {request.POST[f"tarif_{number}"]},
                            {request.POST[f"kapasitas_{number}"]}, {request.POST[f"kapasitas_{number}"]}
                        )
                    """)
                elif "gedung_" in key: # Case LOKASI
                    number = key.split("_")[-1]
                    kode = f"LOC{random.randint(1000000,9999999)}" # kode untuk field kode di LOKASI

                    # INSERT ke LOKASI
                    cursor.execute(f"""
                        INSERT INTO LOKASI (kode, nama_gedung, kota, alamat)
                        VALUES (
                            '{kode}', '{request.POST[f"gedung_{number}"]}',
                            '{request.POST[f"kota_{number}"]}', '{request.POST[f"alamat_{number}"]}'
                        )
                    """)

                    # INSERT ke LOKASI_PENYELENGGARAAN_EVENT
                    cursor.execute(f"""
                        INSERT INTO LOKASI_PENYELENGGARAAN_EVENT (kode_lokasi, id_event)
                        VALUES ('{kode}', '{id_event}')
                    """)
            
        messages.add_message(request, messages.SUCCESS, f"Tambah event berhasil!")
        return redirect("users:daftar_event")


    context = {}

    with connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT DISTINCT nama_tema FROM TEMA
        """)
        context["tema_lst"] = [
            (idx+1 ,tema[0], False) for idx,tema in enumerate(cursor.fetchall())
        ] # Get semua tuple (nomor, id_event, nama_tema)

    return render(request, "users/tambah_event.html", context=context)


users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- CSS External -->
    <link rel="stylesheet" href="{% static 'users_css/users.css' %}">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    
    <title>Event+</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-1">
      <div class="container">
        <a class="navbar-brand" href="{% url 'users:landing' %}">Event+</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:landing' %}">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          
          <!-- Case belum login -->
          {% if not request.session.pengguna %}
            <a href="{% url 'users:login' %}">
              <button class="btn btn-info">
                Login
              </button>
            </a>
          <!-- Case sudah login -->
          {% else %}
            <h5 class="text-light m-0 p-0 mr-2">Selamat datang, {{request.session.pengguna}}</h5>
            <a href="{% url 'users:logout' %}">
              <button class="btn btn-danger">
                Logout
              </button>
            </a>
          {% endif %}

        </div>
        </div>
    </nav>


    <div class="main-container bg-3">
        {% block content %}
        {% endblock %}
    </div>


    <div class="d-flex justify-content-center align-items-center height-nav bg-1 text-light">
        Made by Kelompok 3 - Basis Data (J) Reguler Gasal 2020/2021
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
    <!-- JS External -->
    <script src="{% static 'users_js/reg_organizer.js' %}"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

users/templates/users/daftar_event.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<h3 class="text-center py-4">Daftar Event</h3>

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}} fade show" role="alert">
      {{message}}
    </div>
  {% endfor %}
{% endif %}
      
<table class="table table-hover table-bordered" id="daftar-item-table">
    <thead>
      <tr class="table-light" id="table-header">
        <th>No</th>
        <th>Tema Event</th>
        <th>Nama Event</th>
        <th>Lokasi</th>
        <th>Tanggal</th>
        <th>Jam</th>
        <th>Kapasitas Total</th>
        <th>Kapasitas Total Tersedia</th>

        {% ifequal request.session.tipe "Pengunjung" %}
        <th>Pesan Tiket</th>
        {% endifequal %}

        {% ifequal request.session.tipe "Perusahaan" %}
        <th>Edit Event</th>
        <th>Delete Event</th>
        {% endifequal %}

        {% ifequal request.session.tipe "Individu" %}
        <th>Edit Event</th>
        <th>Delete Event</th>
        {% endifequal %}
      </tr>
    </thead>
    <tbody class="item-table">
      {% block table %}
      {% endblock %}
        {% for nama, tema, kapasitas_total,kapasitas_tersedia, tanggal, jam, lokasi, organizer, is_dimiliki,is_active, id_event in events %}
        <tr class="table-light">
            <td>{{ forloop.counter }}</td>
            <td>{{ tema }}</td>
              <td>{{ nama }}</td>
            <td>{{ lokasi }}</td>
            <td>{{ tanggal }}</td>
            <td>{{ jam }}</td>
            <td>{{ kapasitas_total }}</td>
            <td>{{ kapasitas_tersedia }}</td>

            {% ifequal request.session.tipe "Pengunjung" %}
            <td><a href="/#">Pesan</a></td>
            {% endifequal %}

            {% if not is_active %}
            <td>X</td>
            <td>X</td>
            {% elif request.session.tipe == "Perusahaan" or request.session.tipe == "Individu" %}
            
              {% if is_dimiliki %}
              <td>
                <a href="{% url 'users:update_event' id_event %}">
                  <button class="btn btn-primary">
                    Edit
                  </button>
                </a>
              </td>
              <td>
                <a href="{% url 'users:delete_event' id_event %}">
                  <button class="btn btn-danger">
                    Delete
                  </button>
                </a>
              </td>
              {% else %}
              <td>X</td>
              <td>X</td>
              {% endif %}
            {% endif %}

          </tr>
        {% endfor %}
      </tbody>
</table>

{% endblock %}

users/templates/users/index.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Event+</h1>
    <p class="lead">Organizing events made easy</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <a href="{% url 'profil_pengguna:profile' %}"><u>Profile anda</u></a>
      <br>
      {% ifequal request.session.tipe "Pengunjung" %}
        <a href="{% url 'dompet:dompet_view' %}"><u>Lihat dompet saya</u></a>
        <br>
        <a href="{% url 'testimoni:testimoni_view' %}"><u>Lihat testimoni saya</u></a>
        <br>
        <a href="{% url 'testimoni:create_testimoni' %}"><u>Buat Testimoni</u></a>
        <br>
      {% endifequal %}
      {% ifequal request.session.tipe "Perusahaan" %}
        <a class="btn btn-primary btn-info" href="{% url 'users:daftar_event' %}" role="button">Lihat Event Saya</a>
        <a class="btn btn-primary btn-info" href="{% url 'users:tambah_event' %}" role="button">Buat Event</a>
      {% endifequal %}
    {% else %}
      <p>Daftarkan diri anda sekarang</p>
      <p class="lead">
        <a class="btn btn-primary btn-info" href="{% url 'users:login' %}" role="button">Login</a>
        <a class="btn btn-primary btn-primary" href="{% url 'users:register_pengunjung' %}" role="button">Register Pengunjung</a>
        <a class="btn btn-primary btn-secondary" href="{% url 'users:register_organizer' %}" role="button">Register Organizer</a>
      </p>
    {% endif %}
    <br>
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar Event</h3>
      <br>
      <input type="text" id="myInput" placeholder="Search for names.." title="Type in a name">
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>Tema Event</th>
                    <th>Nama Event</th>
                    <th>Organizer</th>
                    <th>Lokasi</th>
                    <th>Tanggal</th>
                    <th>Jam</th>
                    <th>Kapasitas Total</th>

                    {% if request.session.tipe == "Pengunjung" or not request.session.tipe %}
                    <th>Pesan Tiket</th>
                    {% endif %}

                    {% ifequal request.session.tipe "Perusahaan" %}
                    <th>Edit Event</th>
                    <th>Delete Event</th>
                    {% endifequal %}

                    {% ifequal request.session.tipe "Individu" %}
                    <th>Edit Event</th>
                    <th>Delete Event</th>
                    {% endifequal %}
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for nama, tema, kapasitas_total,kapasitas_tersedia, tanggal, jam, lokasi, organizer, is_dimiliki,is_active, id_event in events %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ tema }}</td>
                          <td>{{ nama }}</td>
                        <td>{{ organizer }}</td>
                        <td>{{ lokasi }}</td>
                        <td>{{ tanggal }}</td>
                        <td>{{ jam }}</td>
                        <td>{{ kapasitas_total }}</td>

                        {% if request.session.tipe == "Pengunjung" or not request.session.tipe %}
                        <td><a href="/#">Pesan</a></td>

                        {% elif request.session.tipe == "Perusahaan" or request.session.tipe == "Individu" %}
                        
                          {% if is_dimiliki and is_active %}
                          <td>
                            <a href="{% url 'users:update_event' id_event %}">
                              <button class="btn btn-primary">
                                Edit
                              </button>
                            </a>
                          </td>
                          <td>
                            <a href="{% url 'users:delete_event' id_event %}">
                              <button class="btn btn-danger">
                                Delete
                              </button>
                            </a>
                          </td>
                          {% else %}
                          <td>X</td>
                          <td>X</td>
                          {% endif %}
                        {% endif %}

                      </tr>
                    {% endfor %}
                  </tbody>
            </table>

            <!-- The Modal -->
            <div class="modal" id="deleteItemModal">
              <div class="modal-dialog">
                  <div class="modal-content">
                  <!-- Modal Header -->
                  <div class="modal-header">
                      <h4 class="modal-title">Delete Item</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                    <!-- Modal body -->
                    <div class="modal-body">
                      Apakah kamu yakin akan menghapus Item ini?
                    </div>
                    <!-- Modal footer -->
                  <div class="modal-footer">
                      <button type="button" class="btn btn-green yes-delete" data-dismiss="modal">Ya</button>
                      <button type="button" class="btn btn-green" data-dismiss="modal">Tidak</button>
                </div>
              </div>
            </div>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}

users/templates/users/register_organizer.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="p-2 pb-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3">Event+ - Registrasi Organizer</h3>

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'users:register_organizer' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="d-flex">
            <div class="form-check mr-2">
                <input class="form-check-input" type="radio" name="tipe_organizer" id="individu" value="Individu" checked>
                <label class="form-check-label" for="individu">
                Individu
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="tipe_organizer" id="perusahaan" value="Perusahaan">
                <label class="form-check-label" for="perusahaan">
                Perusahaan
                </label>
            </div>
        </div>

        <div class="pb-1 mt-3">Email</div>
        <div class="form-group">
          <input name="email" value="{{request.POST.email}}" type="email" class="form-width form-control" aria-describedby="emailHelp" placeholder="Enter email" required>
        </div>
        <div class="pb-1">Password</div>
        <div class="form-group">
          <input name="password" type="password" class="form-width form-control" placeholder="Password" required>
        </div>
        <div class="pb-1">NPWP</div>
        <div class="form-group">
          <input name="npwp" value="{{request.POST.npwp}}" type="text" class="form-width form-control" placeholder="NPWP" required>
        </div>
        <div class="pb-1">No. KTP</div>
        <div class="form-group">
          <input name="ktp" value="{{request.POST.ktp}}" type="text" class="form-width form-control" placeholder="Nomor KTP" required>
        </div>
        <div class="pb-1" id="nama_label">Nama Lengkap (2 kata)</div>
        <div class="form-group">
          <input id="nama_input" value="{{request.POST.nama}}" name="nama" type="text" class="form-width form-control" placeholder="ex: John Doe" required>
        </div>
        <div class="pb-1">Alamat</div>
        <div class="form-group">
          <input name="alamat" value="{{request.POST.alamat}}" type="text" class="form-width form-control" placeholder="Alamat" required>
        </div>

        <div class="d-flex w-100 justify-content-around">
            <button type="submit" class="btn btn-success">Register</button>
            <a href='{% url "users:landing" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>

      </form>
</div>

{% endblock %}

users/templates/users/register_pengunjung.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">Event+ - Registrasi Pengunjung</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'users:register_pengunjung' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Email</div>
        <div class="form-group">
          <input type="email" name="email" value="{{request.POST.email}}" class="form-width form-control" aria-describedby="emailHelp" placeholder="Enter email" required>
        </div>
        <div class="pb-1">Password</div>
        <div class="form-group">
          <input type="password" name="password" class="form-width form-control" placeholder="Password" required>
        </div>
        <div class="pb-1">Nama Lengkap (2 kata)</div>
        <div class="form-group">
          <input type="text" name="nama" value="{{request.POST.nama}}" class="form-width form-control" placeholder="ex: John Doe" required>
        </div>
        <div class="pb-1">Alamat</div>
        <div class="form-group">
          <input type="text" name="alamat" value="{{request.POST.alamat}}" class="form-width form-control" placeholder="Alamat" required>
        </div>

        <div class="d-flex w-100 justify-content-around">
            <button type="submit" class="btn btn-success">Register</button>
            <a href='{% url "users:landing" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>

      </form>
</div>

{% endblock %}